apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vpa
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable-vpa
      version: "4.4.1"
  interval: 1h0m0s
  releaseName: vpa
  targetNamespace: kube-system