apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kepler
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kepler
      sourceRef:
        kind: HelmRepository
        name: kepler
      version: "0.4.3"
  interval: 1h0m0s
  releaseName: kepler
  targetNamespace: kepler